/' Analisis
    Un cliente que necesita comprar plantas.
    Un negocio que vende plantas.
        Existen tipos de plantas.
        Cada planta tiene un precio.
        Existe una transaccion de la venta de las plantas.
    Objetivo:
        Identificar a las clases candidatas.
        Identificar los atributos de cada clase.
        Identificar sus relaciones.
        Encontrar fallas o inconsitencias en el diagrama.
'/

@startuml
class Venta{
    fecha
    hora
    detalles: DetalleVenta
    total
    
    Crear()
    Mostrar()
    ConocerDetalleVenta()
    CalcularTotal()
}
note left
    Clase mas instanciada: 
    Clase principal
end note

'La venta y la planta tienen una relacion *..*, se agrega un detalle para especificar'
class DetalleVenta{
    planta: Planta
    cantidad
    subtotal

    Crear()
    Mostrar()
    ConocerPlanta()
    CalcularSubtotal()
}

class Planta{
    nombre
    descripcion
    id
    cantidad
    precio
    tipo: TipoPlanta

    Crear()
    Mostrar()
    ConocerTipoPlanta()
}

note left
    Hay diferentes plantas que
    pueden coincidir en un tipo,
    sin embargo siguen siendo "razas"
    diferentes
end note
class TipoPlanta{
    nombre
    idTipo

    Crear()
    Mostrar()

}

Venta *-> "1..*" DetalleVenta
DetalleVenta --> "1" Planta
Planta --> "1" TipoPlanta
@enduml