/' Venta de discos analisis:
Consiste en un sistema de informacion que procesa las ventas de discos.
- Multiples sellos discograficos
    nombre, el domicilio, el teléfono, el e-mail.
- Multiples generos musicales
    número y una descripción.

- Venta (transaccion)
    registra la fecha de la venta, nombre del cliente que adquiere el disco, 
    la cantidad comprada de dicho disco, el precio unitario del disco, 
    el importe total de la venta y un descuento en el caso que hubiere.

- Disco
    nombre del álbum, cantidad existente y el precio unitario, el
    año de edición.

- Interpretes
    nombre, apellido, nacionalidad.

Logica de relaciones:
- Cada disco corresponde a un sello discográfico y a un género musical.
    cada sello discográfico comprende muchos discos, y hay muchos discos de un mismo
    género musical.
- Cada disco puede tener uno o más intérpretes y por cada intérprete puede
    corresponder uno o más discos.

Se emiten listados de:
 Listados de discos vendidos en el mes.
 Informe de discos que se vendieron del género Romántico.
 Listado alfabético de sellos discográficos.
 Listado de intérpretes según su nacionalidad.
'/

@startuml Discos
class Sello{
    nombre
    domicilio
    telefono
    email

    crear()
    mostrar()
}

class Genero{
    nombre
    descripcion

    crear()
    mostrar()
}

'cantidad en el stock'
class Disco{
    nombre
    cantidad
    añoEdicion
    precio
    sello: Sello
    genero: Genero
    interprete: Interprete

    crear()
    mostrar()
    conocerSello()
    conocerGenero()
    conocerInterprete()
}

class Venta{
    nroVenta
    detalles: DetalleVenta
    nombreCliente
    fecha
    total
    descuento

    crear()
    mostrar()
    conocerDetalleVenta()
    calcularTotal()
}
'El precio unitario permite congelar el precio al momento de la venta'
class DetalleVenta{
    disco: Disco
    precioUnitario
    cantidad

    crear()
    mostrar()
    conocerDisco()
}

class Interprete{
    nombre
    apellido
    nacionalidad

    crear()
    mostrar()
}

Venta *-> "1..*" DetalleVenta
DetalleVenta --> "1" Disco
Disco --> "1" Genero
Disco --> "1" Sello
Disco --> "1..*" Interprete
@enduml